### ISSUE TITLE
getPrayerTimes outputs set<String> which is unsorted

### ISSUE THREAD

**Issue by alimir1** [alhazmy13/PrayerTimesSwift#5]
Since the output of getPrayerTimes is set<String> the prayer timings are random. Maybe a better way to fix it is using [String] instead of sets? By doing so, we know prayer time (for example prayertime[0] = Fajr an so on..)

**Comment by alhazmy13** [comment]
It's return a sorted set, for example:

``` Swift
let myPrayerTime = PrayerTimes(caculationmethod: .Makkah, asrJuristic: .Shafii, adjustHighLats: .None, timeFormat: .Time12)
 let prayerTimes = myPrayerTime.getPrayerTimes(NSCalendar.currentCalendar(), latitude: 24.7993689, longitude: 46.6176563, tZone: 3)
for time in prayerTimes{
            print(time)
}
```

**Comment by alimir1** [comment]
I think using a dictionary would be better so that we can easily fetch a particular prayer time:

prayerTimes["Dhuhr"] // 12:34pm

prayerTimes["Fajr"] // 5:32am
