### ISSUE TITLE
Swift 4 issue

### ISSUE THREAD

**Issue by tariqul000** [alhazmy13/PrayerTimesSwift#7]
Thank you so much I already use your library for android and now i want to use for ios but Many issues with Xcode 9.4.1 and Swift 4. Kindly update for Swift 4.

**Comment by mehdihdev** [comment]
Its been 4 years since anyone has updated this repository, could you please update this library for Swift 4.

**Comment by alhazmy13** [comment]
Should be fixed with https://github.com/alhazmy13/PrayerTimesSwift/releases/tag/v1.2.0
